import type { Metadata } from "next";
import "../sass/main.scss";
import { Geist, Geist_Mono } from "next/font/google";
import { Header } from "@/components/layout/header";
import { Footer } from "@/components/layout/footer";
import { getGlobalSettings } from "./data/loaders";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function loader() {
  const {data} = await getGlobalSettings();
  if (!data) throw new Error("Global settings not found");
  return {
    header: data?.header,
    footer: data?.footer,
  };
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
const { header, footer } = await loader();
console.dir(footer, {depth: null});
return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>
        <Header data={header} />
        {children}
        <Footer data ={footer} />
      </body>
    </html>
  );
}
